Unleash.sln, tests/Unleash.Tests.Benchmarks/Program.cs, tests/Unleash.Tests.Benchmarks/Unleash.Tests.Benchmarks.csproj, tests/Unleash.Tests.Benchmarks/packages.config, tests/Unleash.Tests/Basic/VariantsTest.cs, tests/Unleash.Tests/Communication/BaseUnleashApiClientTest.cs, tests/Unleash.Tests/Serialization/DynamicJsonSerializerTests.cs, tests/Unleash.Tests/Unleash.Tests.csproj, tests/Unleash.Tests/packages.config
- Updated some packages (Check packages.config)
- Unloaded breaking sample projects (Put in other solution or something should be best)
=> Ajusting paths and unbreaking CI

src/Unleash/Strategies/StrategyUtils.cs, src/Unleash/Unleash.csproj, tests/Unleash.Tests/Strategy/StrategyUtilsTests.cs, tests/Unleash.Tests/Unleash.Tests.csproj, tests/Unleash.Tests/packages.config
Use murmur3 hash algorithm.
Tests added to verify compatability with generated hashed from Java and Go clients / implementations.
=> Use murmur3 hash algorithm (#7)

src/Unleash/DefaultUnleash.cs, src/Unleash/UnleashContext.cs, src/Unleash/UnleashSettings.cs, tests/Unleash.Tests/Unleash.Tests.csproj, tests/Unleash.Tests/UnleashContextTests.cs, tests/Unleash.Tests/UnleashSettingsTests.cs
Align static fields implementation with Java client.
=> Add support for static context fields

src/Unleash/DefaultUnleash.cs, src/Unleash/Internal/ActivationStrategy.cs, src/Unleash/Internal/Constraint.cs, src/Unleash/Internal/Operator.cs, src/Unleash/Strategies/ApplicationHostnameStrategy.cs, src/Unleash/Strategies/ConstraintUtils.cs, src/Unleash/Strategies/DefaultStrategy.cs, src/Unleash/Strategies/FlexibleRolloutStrategy.cs, src/Unleash/Strategies/GradualRolloutRandomStrategy.cs, src/Unleash/Strategies/GradualRolloutSessionIdStrategy.cs, src/Unleash/Strategies/GradualRolloutUserIdStrategy.cs, src/Unleash/Strategies/IStrategy.cs, src/Unleash/Strategies/RemoteAddressStrategy.cs, src/Unleash/Strategies/StrategyUtils.cs, src/Unleash/Strategies/UnknownStrategy.cs, src/Unleash/Strategies/UserWithIdStrategy.cs, src/Unleash/UnleashContext.cs, tests/Unleash.Tests/Strategy/FlexibleRolloutStrategyTest.cs, tests/Unleash.Tests/Strategy/StrategyTest.cs, tests/Unleash.Tests/Unleash.Tests.csproj
Last piece of the puzzle for the client specification tests to pass.
=> Align constraints functionality with Java client (#39)

src/Unleash/ClientFactory/IUnleashClientFactory.cs, src/Unleash/ClientFactory/UnleashClientFactory.cs
=> fix: add custom stratgies to factory methods

build.ps1
* Hardware:
* Toolchain:
* SDK:
=> fix: build script

samples/WebApp/packages.config
Bumps bootstrap from 3.0.0 to 3.4.1.
Signed-off-by: dependabot[bot] <support@github.com>
* Hardware:
* Toolchain:
* SDK:
=> Bump bootstrap from 3.0.0 to 3.4.1 in /samples/WebApp

.github/workflows/release.yml, README.md, build.cake, src/Unleash/Unleash.csproj, tests/Unleash.Tests/Communication/BaseUnleashApiClientTest.cs
update links and workflows after branch renaming.
Also fixes Cake issues by using the changes from @daveleek's PR #84 (thanks for figuring that out and kudos! 😄).
=> chore: rename master -> main; update links

.github/workflows/prs.yml, .github/workflows/release.yml, src/Unleash/Internal/Constraint.cs, src/Unleash/Internal/Operator.cs, src/Unleash/Strategies/ConstraintUtils.cs, src/Unleash/Strategies/Constraints/DateConstraintOperator.cs, src/Unleash/Strategies/Constraints/IConstraintOperator.cs, src/Unleash/Strategies/Constraints/NumberConstraintOperator.cs, src/Unleash/Strategies/Constraints/SemverConstraintOperator.cs, src/Unleash/Strategies/Constraints/StringConstraintOperator.cs, src/Unleash/Unleash.csproj, src/Unleash/UnleashContext.cs, tests/Unleash.Tests/Communication/UnleashApiClient_FetchToggles_Tests.cs, tests/Unleash.Tests/Communication/UnleashApiClient_RegisterClient_Tests.cs, tests/Unleash.Tests/Communication/UnleashApiClient_SendMetrics_Tests.cs, tests/Unleash.Tests/Integration/ClientSpecificationTests.cs, tests/Unleash.Tests/Integration/UnleashContextDefinition.cs, tests/Unleash.Tests/Strategy/Constraints/DateConstraintOperator_Tests.cs, tests/Unleash.Tests/Strategy/Constraints/NumberConstraintOperator_Tests.cs, tests/Unleash.Tests/Strategy/Constraints/SemverConstraintOperator_Tests.cs, tests/Unleash.Tests/Strategy/Constraints/StringConstraintOperator_Tests.cs, tests/Unleash.Tests/Strategy/StrategyTest.cs, tests/Unleash.Tests/Unleash.Tests.csproj, tests/Unleash.Tests/packages.config
Adds support for additional constraint operators: 
Semantic Versioning
SEMVER_EQ
SEMVER_GT
SEMVER_LT
Numbers
NUM_EQ
NUM_GT
NUM_GTE
NUM_LT
NUM_LTE
Date
DATE_AFTER
DATE_BEFORE
Strings
STR_ENDS_WITH
STR_STARTS_WITH
STR_CONTAINS
Also adds inverted feature to constraints
#85 
- Added a series of unittests to verify functionality
- Ran the spec tester
=> Issue #85: add support for new constraint operators

.github/workflows/release.yml
Changes the .NET version used for compilation to .NET 5
Infrastructure
This works in prs.yml pipeline
=> Bump release pipeline to .NET 5

src/Unleash/DefaultUnleash.cs, src/Unleash/IUnleash.cs
Extend the `IUnleash` interface with a new `GetVariants` method overload that allows passing UnleashContext as an argument.
Fixes #92
Manual test by referencing a project and using the `IUnleash` interface.
* Hardware:
* Toolchain:
* SDK:
=> Extend IUnleash interface with GetVariants implementation considering UnleashContext

src/Unleash/Internal/CachedFilesLoader.cs, src/Unleash/Scheduling/FetchFeatureTogglesTask.cs, tests/Unleash.Tests/IOTests.cs, tests/Unleash.Tests/MockedUnleashSettings.cs, tests/Unleash.Tests/Unleash.Tests.csproj
Wraps IO writes in try catch so we can fail more gracefully: https://unleash-community.slack.com/archives/CGP2MCHPF/p1666073059611789
=> fix: wrap IO tasks in try catch so we can fail more gracefully

src/Unleash/Scheduling/SystemTimerScheduledTaskManager.cs
Addressing System.Collections.Generic.KeyNotFoundException we have experienced.
Preventing a KeyNotFoundException if timer does not exist
- [X ] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* Toolchain:
* SDK:
=> Added key exist check to timers

src/Unleash/Strategies/RemoteAddressStrategy.cs, src/Unleash/Utilities/IPCIDRAddressRange.cs, tests/Unleash.Tests/Strategy/RemoteAddressStrategyTest.cs, tests/Unleash.Tests/Unleash.Tests.csproj, tests/Unleash.Tests/Utilities/IPCIDRAddressRange_Tests.cs
Adds support for IP CIDR (IPv4 & IPv6) in RemoteAddressStrategy
Added tests specificly for the added feature. Ran all the existing tests
=> feat: add support for ip cidr in remote address strategy

src/Unleash/DefaultHttpClientFactory.cs
This enables the etag logic in unleash.
=> feat: enable caching from unleash

README.md
=> fix: point links to correct destination

README.md
Adds to the README a section about logging and plugging in a custom logger
Testing with a sample app to verify the custom logging works
=> docs: update README with info on logging

build.cake, src/Unleash/DefaultUnleash.cs, src/Unleash/Internal/ActivationStrategy.cs, src/Unleash/Internal/FeatureEvaluationResult.cs, src/Unleash/Internal/FeatureToggle.cs, src/Unleash/Unleash.csproj, src/Unleash/Variants/VariantUtils.cs, tests/Unleash.Tests/Unleash.Tests.csproj, tests/Unleash.Tests/Variants/StrategyVariantTests.cs
Implementation of Strategy Variants
- By running specifications locally
- Added specific unit tests
=> feat: implement strategy variants

src/Unleash/DefaultUnleash.cs
=> feat: warn when IsEnabled falls back to returning default value

src/Unleash/Unleash.csproj
Includes the repo README as NuGet readme file in the .nupkg
=> feat: reference README.md as NuGet package readme in Unleash.csproj

README.md, src/Unleash/Unleash.csproj
Adds support for .NET 4.8 and 4.7.2
Making a beta nuget release 3.4.1 of unleash, then going to download the package and inspect
=> feat: support .NET 4.8 and 4.7.2

src/Unleash/DefaultUnleash.cs, src/Unleash/Internal/Variant.cs, src/Unleash/Variants/VariantDefinition.cs, tests/Unleash.Tests/Integration/ClientSpecificationTests.cs, tests/Unleash.Tests/Variants/VariantsTests.cs
implements feature_enabled for variant responses and adds relevant unit tests
Adding new relevant unit tests and running the client spec tests
=> feat: implement feature enabled for variant response

src/Unleash/UnleashContext.cs
In looking at our application which uses the dotnet Unleash client we found that a large amount of memory was being allocated by the client when checking if a flag was enabled:
Looking at the callstack it can be seen that these allocations come from creating dictionaries when cloning the provided `UnleashContext`.
There are three optimizations that can be made:
1. Don't use `Linq.ToDictionary`. Under the hood this will create an empty dictionary and add items to it one by one, causing excess allocations as the dictionary internals grow. Instead create a new dictionary providing the old one as a source, this will create a fresh dictionary with the correct size right off the bat.
2. Dont assign a dictionary to `Properties` in `UnleashContext` or `Builder` unless we need to. In all cases we …
=> Reduce allocations when creating a new UnleashContext

.github/workflows/prs.yml
This enables the pull request action on pull requests
=> feat: run tests on pull requests

src/Unleash/Scheduling/FetchFeatureTogglesTask.cs, src/Unleash/Scheduling/SystemTimerScheduledTaskManager.cs
Changes intermittent errors to log level warn
Fixes #209
=> chore: lower the loglevels for intermittent errors

src/Unleash/Strategies/FlexibleRolloutStrategy.cs, tests/Unleash.Tests/Strategy/FlexibleRolloutStrategyTest.cs
Allow stickiness to be an empty string.
Fixes #215
=> :bug: Fix empty user Id return false from IsEnabled #215

README.md
Fixes chose type (should be choose)
=> chore(docs): typos choose not chose

README.md, samples/WebApp/Global.asax.cs, samples/WebApplication/Startup.cs, samples/WinFormsApp/Program.cs, src/Unleash/Communication/UnleashApiClient.cs, src/Unleash/Communication/UnleashApiClientRequestHeaders.cs, src/Unleash/Events/ErrorType.cs, src/Unleash/Internal/UnleashServices.cs, src/Unleash/Internal/UnleashSettingsValidator.cs, src/Unleash/Scheduling/ClientRegistrationBackgroundTask.cs, src/Unleash/Scheduling/FetchFeatureTogglesTask.cs, src/Unleash/UnleashSettings.cs, tests/Unleash.Tests/ClientFactory/SyncStartupUnitTest.cs, tests/Unleash.Tests/Communication/CustomHeadersUnitTest.cs, tests/Unleash.Tests/Communication/UnleashApiClient_Project_Tests.cs, tests/Unleash.Tests/ExampleTests.cs, tests/Unleash.Tests/IOTests.cs, tests/Unleash.Tests/Internal/ErrorEvents_Tests.cs, tests/Unleash.Tests/MockedUnleashSettings.cs
https://linear.app/unleash/issue/2-2430/revert-autogenned-instance-id-net
Reverts: #226
=> chore: Revert "feat: automatically generated instanceId (#226)"

src/Unleash/UnleashSettings.cs
Does what it says on the tin, first steps towards closing #221
=> chore: add deprecation warning to settable json serializer

samples/DotnetCore/DotnetCore.csproj, samples/DotnetCore/DotnetCore.sln, samples/DotnetCore/Program.cs
I used this to validate that this worked against Edge/Unleash, seems a shame to throw it away since there's no easily runnable sample in this repo at the moment
=> chore: add dotnet core sample

src/Unleash/Unleash.csproj
Should have 32 windows support
=> chore: bump yggdrasil

src/Unleash/Unleash.csproj
Adds support for .NET Framework
=> chore: bump yggdrasil to 1.0.5

README.md, src/Unleash/Unleash.csproj
Updates references to the repository.
Also, update refs to old heroku app and replaces them with demo site
=> chore: update repository references
