.github/CONTRIBUTING.md
README.md

Fixes #34 
- Added contribution guide based on https://www.contributor-covenant.org/ version 1.4
Should increment over time, adding more scoped guides leveraging the project
- Changed ci status badge

Adding contributing guide

---

src/Unleash/DefaultUnleash.cs

fixes #10
- Changes the default behavior of the `DefaultUnleash` constructor to always include the default strategies, regardless of whether any custom strategies were provided. 
- Provides a constructor overload to allow overriding the default strategies. _Beware_, that overriding this without any custom strategies will yield an empty strategy map. I'm sure whether this is acceptable. 
- Fixes a minor typo.
**This implementation will be a breaking change for anyone currently passing custom strategies, expecting only their custom strategies to apply.**

Changes the behavior to always include the default strategies

---

README.md
samples/WebApp/Global.asax.cs
samples/WinFormsApp/Program.cs
src/Unleash/Communication/UnleashApiClient.cs
src/Unleash/UnleashSettings.cs
tests/Unleash.Tests/Communication/BaseUnleashApiClientTest.cs
tests/Unleash.Tests/Communication/UnleashHttpClientFactory_RegisterHttpClient_Tests.cs

Unleash API URL path /api/ shouldn't be hard-coded, as it prevents custom URLs/paths.

Use compliant API URL (#8)

---

samples/WebApp/Web.config
samples/WebApp/WebApp.csproj
samples/WebApp/packages.config

Fixes CS1617 build error occurring on clean build from master on VS 2019, ref. https://developercommunity.visualstudio.com/content/problem/519531/c-7x-versions-do-not-seem-to-work-in-vs2019.html.

Upgrade DotNetCompilerPlatform package (relates to #30)

---

src/Unleash/Unleash.csproj

CSProj files have been updated to enable SourceLink in your nuget
---
*[This pull request was created with an automated workflow]*
I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.
**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)
You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx
If you are interesting about this automated workflow …

[PR] The proj files have been updated to enable SourceLink

---

src/Unleash/Scheduling/SystemTimerScheduledTaskManager.cs
tests/Unleash.Tests/Scheduling/SystemTimerScheduledTaskManagerTests.cs

Fixes #63 
The fix changes the way the Timer is used. Instead of changing the Timer's dueTime on each callback, dueTime is only used for the initial delay before firing the callback the first time. It uses the period to specify the interval between each firing of the callback. I think this is how the Timer is supposed to be used.
Verified in our production environment, which runs multiple instances of an ASP.NET Core web application in Azure. 
Our configuration looks like this:
```csharp
var unleashSettings = new UnleashSettings
{
AppName = appName,
InstanceTag = Environment.MachineName,
SendMetricsInterval = TimeSpan.FromMinutes(1),
UnleashApi = new Uri(unleashUrl),
CustomHttpHeaders = new Dictionary<string, string>
{
{"Authorization", clientSecret}
},
ScheduledTaskManager = new …
```

Fix timing bug in SystemTimerScheduledTaskManager

---

README.md
src/Unleash/Communication/UnleashApiClient.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/UnleashSettings.cs
tests/Unleash.Tests/Communication/UnleashApiClient_Project_Tests.cs
tests/Unleash.Tests/Mock/MockHttpMessageHandler.cs
tests/Unleash.Tests/Unleash.Tests.csproj

This PR aims to add the projectId query parameter feature to the unleash-client-dotnet.
It does this by adding a setting for ProjectId to UnleashSettings. This setting is carried over to UnleashApiClient and there gets added to the feature toggles uri.
#69 
It was tested by adding unit tests specifically for this feature and by running the entire test suite.
Also tested by debugging the WebApplication project in this repo with the different projectids from the demo host.
One unittest fails, but that also fails on master without my changes.: `ShouldBeEnabledWhenExpected`

feat: support project query parameter (#69)

---

README.md
src/Unleash/Strategies/FlexibleRolloutStrategy.cs
tests/Unleash.Tests/Strategy/FlexibleRolloutStrategyTest.cs

Intends to add support for custom stickiness parameters
#71 
Added four new tests with data from the feature specification

feat: flexible rollout support custom stickiness #71

---

src/Unleash/Unleash.csproj

This PR adds support for versioning the NuGet package via build parameter.
If no version number, 1.0.0 will be used (for instance while building locally)
Locally by providing various build versions on the command line to msbuild and looking at the outputs of the build

nuget: take build parameter as version variable

---

src/Unleash/Variants/VariantDefinition.cs
src/Unleash/Variants/VariantUtils.cs
tests/Unleash.Tests/Variants/VariantUtilsTests.cs

This is a Work In Progress
This PR intends to implement issue #72. Custom stickiness for variants.
#72 

feat: variants custom stickiness

---

src/Unleash/Internal/Constraint.cs
src/Unleash/Internal/Operator.cs
src/Unleash/Strategies/ConstraintUtils.cs
src/Unleash/Strategies/Constraints/DateConstraintOperator.cs
src/Unleash/Strategies/Constraints/NumberConstraintOperator.cs
src/Unleash/Strategies/Constraints/SemverConstraintOperator.cs
src/Unleash/Strategies/Constraints/StringConstraintOperator.cs
tests/Unleash.Tests/Strategy/Constraints/ConstraintUtilsTests.cs

A potential fix to the problem that invalid operators cast exception and aborts deserialization

improvement: convert operators to const strings

---

.github/workflows/release.yml

A fix for the issue of release-workflow not removing -beta.n prerelease version info, only -beta

improvement: fix build versions allow beta.n

---

src/Unleash/DefaultUnleash.cs
src/Unleash/IUnleash.cs

Changed the overload of GetVariant that accepts an UnleashContext from being private to public and added it to the IUnleash interface. Updated some comments on the three GetVariant methods since they seem to be outdated regarding return value and stickiness, but I can change this back if I am mistaken.
Fixes [74](https://github.com/Unleash/unleash-client-dotnet/issues/74)
Ran the cake script before and after the change. 3 failing unit tests before and after: Unleash.Tests.Communication.UnleashApiClient tests that do not seem to authenticate properly. Atleast I get a prompt for authentication when I try to reach out to http://unleash.herokuapp.com/api/

make getvariant public

---

build.cake
src/Unleash/UnleashSettings.cs

Changes the default SendMetricsInterval to 60s as per our [documentation](https://docs.getunleash.io/sdks#server-side-sdk-compatibility-table)
Fixes # https://github.com/Unleash/unleash-client-dotnet/issues/105
* Hardware:
* Toolchain:
* SDK:

Changed default SendMetricsInterval to 60s

---

README.md
src/Unleash/DefaultUnleash.cs
src/Unleash/IUnleash.cs
src/Unleash/Internal/EventCallbackConfig.cs
src/Unleash/Internal/FeatureToggle.cs
src/Unleash/Internal/ImpressionEvent.cs
src/Unleash/Serialization/JsonSerializerTester.cs
tests/Unleash.Tests/App_Data/impressiondata-v2.json
tests/Unleash.Tests/DefaultUnleashTests.cs
tests/Unleash.Tests/Internal/CachedFilesLoader_Bootstrap_Tests.cs
tests/Unleash.Tests/Internal/ImpressionData_Tests.cs
tests/Unleash.Tests/Mock/MockApiClient.cs
tests/Unleash.Tests/Serialization/DynamicJsonSerializerTests.cs
tests/Unleash.Tests/Strategy/Segments_Tests.cs
tests/Unleash.Tests/Unleash.Tests.csproj
tests/Unleash.Tests/Variants/VariantUtilsTests.cs

Aims to add an event system to the SDK and a first implementation for impression data/events: https://docs.getunleash.io/advanced/impression-data#impression-event-data
#108

Feature: event system and impression data events

---

README.md
src/Unleash/DefaultHttpClientFactory.cs
tests/Unleash.Tests/DefaultUnleashTests.cs
tests/Unleash.Tests/Mock/HttpClientFactoryMock.cs
tests/Unleash.Tests/Unleash.Tests.csproj

Attempts to solve issue #114 by adding an overrideable method for `HttpClient` instantiation to `DefaultHttpClientFactory`.
Inherit from `DefaultHttpClientFactory` and override the method `CreateHttpClientInstance` to take control of instantiation
#114 
Unit tests

issue 114/improvement: move creation of httpclient instance to virtual property

---

README.md

This change merges content from docs.getunleash.io into the readme
Most of the content already existed in the readme, so the changes are
primarily rewordings and clarifications.
There's also a few cleanup changes:
- Promote a fair few headings. It seems like a lot of the headings were
mistakenly nested under "Getting started", so I have promoted them so
that they're now they're own proper subsections.
- Updated links to the docs.getunleash.io articles
We're making a change to the documentation on docs.getunleash.io. Keeping the docs in sync with the SDKs and their readmes is difficult and a lot of manual work, so we've decided to move to generating the SDK documentation from the project readmes. Moving forward, all SDK-specific documentation will be replaced with the SDKs' respective …

docs: merge content from docs.getunleash.io

---

src/Unleash/Strategies/FlexibleRolloutStrategy.cs
tests/Unleash.Tests/Strategy/FlexibleRolloutStrategyTest.cs

This allows the flexible rollout strategy to correctly fallback to random when no context is passed. Closes #125

add test to check if flexible rollout handles a null context correctly

---

src/Unleash/UnleashSettings.cs
tests/Unleash.Tests/UnleashSettingsTests.cs

This sets the sdk name as well as the version during the client registration.

feat: send sdk name during client registration

---

README.md

This change removes references to `InstanceTag` in the examples.
1. This property doesn't need to be set. The SDK will generate a default if you don't provide it. Removing it simplifies the examples.
2. This property is never explained anywhere in the readme, so it can
be hard to know what it does and what it's used for. Additionally, the
name `InstanceTag` is different from the `InstanceId` that other SDKs
use, making it confusing even to people somewhat familiar with Unleash.

docs: Remove references to `InstanceTag`

---

src/Unleash/DefaultUnleash.cs
tests/Unleash.Tests/Internal/ImpressionData_Tests.cs

Fixes a bug where an app not configuring ImpressionData would throw null refs on toggles with impression data enabled
- Added a unit test
- Ran all unit tests

Fixes a bug where an app not configuring ImpressionData would throw null refs

---

src/Unleash/Communication/UnleashApiClient.cs
tests/Unleash.Tests/Communication/CustomHeadersUnitTest.cs

Unlike the other SDKs (validated in Node and Java), the dotnet SDK does not add the a user agent header. This behavior is inconsistent and can prevent API gateways that are expecting such a header from processing the request.
https://github.com/Unleash/unleash-client-node/blob/main/src/request.ts#L56
No current tests exist to validate these internal-only headers in the dotnet project.
Honestly, I cannot get this to build and run the tests locally.

Add user agent header

---

README.md

There was a comma before the initializer list of the dictionary which made the code snippet not compile properly.

docs: remove comma

---

src/Unleash/Internal/UnleashServices.cs
src/Unleash/UnleashSettings.cs
src/Unleash/Utilities/ToggleBootstrapFileProvider.cs
src/Unleash/Utilities/ToggleBootstrapUrlProvider.cs
tests/Unleash.Tests/Utilities/ToggleBootstrapFileProvider_Tests.cs
tests/Unleash.Tests/Utilities/ToggleBootstrapUrlProvider_Tests.cs

Take UnleashSettings in Bootstrap providers as argument to use as source for services instead of individual arguments that potentially are not created yet

fix: take settings reference instead and use props

---

src/Unleash/Metrics/ToggleCount.cs
tests/Unleash.Tests/Metrics/MetricsBucketTests.cs

This PR adds a test and a fix for an issue we had when counting variants in the `ToggleCount` class. As reported in #138, the old way we counted didn't work.
I've kept the same testing style as applied in the other metrics bucket tests. Testing 100000 counts seems a little excessive, but it should at least prove that it works. Happy to change it if you think it's too much. 
Thanks to @nhathongly for the fix.
Fixes #138
* Firmware version: (I don't know. What do you want here?)
* Hardware: MacOS M1 chip
* Toolchain: dotnet version 7.0.302
* SDK: from …

fix: count variants

---

src/Unleash/DefaultUnleashContextProvider.cs
tests/Unleash.Tests/DefaultUnleashTests.cs

This fixes an issue with Flexible rollout strategy - stickiness would be resolved to an empty (non null) string instead of defaulting to random number when context isn't provided

chore: change context defaults to null - fixes flexiblestrat

---

README.md
src/Unleash/Internal/EventCallbackConfig.cs
src/Unleash/Internal/TogglesUpdatedEvent.cs
src/Unleash/Scheduling/FetchFeatureTogglesTask.cs
tests/Unleash.Tests/Internal/TogglesUpdatedEvent_Tests.cs
tests/Unleash.Tests/Unleash.Tests.csproj

Added new `TogglesUpdatedEvent` that is raised by `FetchFeatureTogglesTask` when there are changes (`result.HasChanged`). This is done to allow dotnet client applications to take any actions, as needed, in response to toggle updates.
Fixes #149
* IDE: Visual Studio Professional 2022 (64-bit) Version 17.4.4
* Client application that uses `unleash-client-dotnet` targets **net 6.0**

Added support for toggle update event

---

src/Unleash/DefaultUnleash.cs
tests/Unleash.Tests/Internal/ImpressionData_Tests.cs

This patches an issue in the SDK where the appName was not being set correctly when applying impression data. This was caused by passing the base context, rather than the enriched context

fix: impression data should now contain static appName even if its not set

---

build.cake

Updates client spec to 4.3.3. Just the easiest way to prove that the new tests work because of the current state of the tests and Linux reasons

Update build.cake to pull 4.3.3 of client spec

---

src/Unleash/Scheduling/FetchFeatureTogglesTask.cs
tests/Unleash.Tests/Internal/TogglesUpdatedEvent_Tests.cs

Raise the `TogglesUpdatedEvent` AFTER the toggles collection is updated in `FetchFeatureTogglesTask`. This will allow clients that provide an event handler to be able to obtain the current toggle state rather than the "old" state.
Fixes # ([160](https://github.com/Unleash/unleash-client-dotnet/issues/160))
* IDE: Visual Studio Professional 2022 (64-bit) Version 17.4.4
* Client application that uses unleash-client-dotnet targets net 6.0

Raise TogglesUpdatedEvent after toggle collection is updated

---

src/Unleash/DefaultUnleash.cs
src/Unleash/Internal/Dependency.cs
src/Unleash/Internal/FeatureToggle.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/Utilities/WarnOnce.cs
tests/Unleash.Tests/App_Data/dependent-features-missing-enabled.json
tests/Unleash.Tests/Integration/ClientSpecificationTests.cs
tests/Unleash.Tests/Internal/Dependent_Features_Tests.cs
tests/Unleash.Tests/Serialization/DynamicJsonSerializerTests.cs
tests/Unleash.Tests/Unleash.Tests.csproj

Adds support for dependent features in .NET SDK. Also adds a warn once component

feat: dependent feature toggles

---

src/Unleash/DefaultUnleash.cs

Starts logging errors (instead of warnings) when unleash instance count is higher than 10

feat: log errors instead of warnings if instance count is over 10

---

src/Unleash/Internal/ActivationStrategy.cs
src/Unleash/Internal/Segment.cs
src/Unleash/Internal/ToggleCollection.cs
tests/Unleash.Tests/Strategy/Segments_Tests.cs

Segment ids were being sent as numbers but deserialized into strings, which can cause deserialization errors. This fix changes the local type of segment ids to be ints
Fixes #173

fix: make segment ids deserialize as ints instead of strings

---

src/Unleash/DefaultUnleash.cs

In looking at our application which uses the dotnet Unleash client we found that a large amount of memory was being allocated by the client:
Looking at the callstack the `Union` call in `DefaultUnleash.DetermineIsEnabledAndStrategy` is what is allocating so many arrays. These allocations can be reduced by replacing the `Union` call with a preallocated `HashSet` (which is what `Union` uses).
The following BenchmarkDotnet code was used to validate that this was better performing:
```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
var summary = BenchmarkRunner.Run<UnionExamples>();
Console.WriteLine(summary);
[MemoryDiagnoser]
public class UnionExamples
{
const int Length = 1000;
readonly IEnumerable<ExampleConstraint> first;
readonly IEnumerable<ExampleConstraint> second; …
```

Improve on Union performance

---

src/Unleash/Communication/UnleashApiClient.cs
tests/Unleash.Tests/Communication/BaseBackoffTest.cs
tests/Unleash.Tests/Communication/UnleashApiClient_Features_Backoff_Tests.cs
tests/Unleash.Tests/Communication/UnleashApiClient_Metrics_Backoff_Tests.cs

Implements a backoff strategy for metrics and features endpoints based on skipping scheduled polls/posts.
Specific failed request responses (401, 403, 404, 429, 500, 502, 503, 504) increases amount of requests to skip.
10 skips in a row is maximum.
401, 403, 404 cause the skip counter to increase to 10 immediately
Unit tests to provoke the behavior has been added

feat: implement skipping backoff strategy

---

src/Unleash/UnleashContext.cs

When calling `IUnleash.IsEnabled` we end up cloning the `UnleashContext`. This cloning is not needed and expensive since the entire `Properties` dictionary needs to be cloned. This case removes the cloning.
Fixes #186
Using the following benchmark (note `IsEnabled2` calls the code proposed in this PR):
```
[MemoryDiagnoser]
public class Benchmark
{
readonly UnleashContext context = new();
readonly DefaultUnleash client = new(new UnleashSettings());
public Benchmark()
{
// Remove this loop to test empty properties
for (int i = 0; i < 10; i++)
{
context.Properties.Add(i.ToString(), i.ToString());
}
}
[Benchmark(Baseline = true)]
public bool Current() => client.IsEnabled("Moo", context);
[Benchmark]
public bool NoClone() => …
```

Don't Clone Context in UnleashContext.ApplyStaticFields

---

src/Unleash/Communication/UnleashApiClient.cs
src/Unleash/DefaultUnleash.cs
src/Unleash/Internal/CachedFilesLoader.cs
src/Unleash/Internal/UnleashExtensions.cs
src/Unleash/LibLog.cs
src/Unleash/Scheduling/FetchFeatureTogglesTask.cs
src/Unleash/Scheduling/SystemTimerScheduledTaskManager.cs
src/Unleash/Strategies/Constraints/SemverConstraintOperator.cs
src/Unleash/Strategies/RemoteAddressStrategy.cs
src/Unleash/Utilities/ToggleBootstrapUrlProvider.cs
src/Unleash/Utilities/WarnOnce.cs

A high number of string allocations were found to come from `DefaultUnleash.DetermineIsEnabledAndStrategy`:
I believe this is due to the logging that's done if the toggle isn't available:
This will always allocate a string even if logging is disabled (or log level Warning is disabled). We should instead be passing a `Func<string>` which is a smaller allocation that will only get evaluated if logging is on.
Also, in looking at this I noticed there was inconsistant checking if a log level was enabled in `LogExtensions` so I will clean that up as well.
Using the following benchmark (note IsEnabled2 has my changes):
```
[MemoryDiagnoser]
public class Benchmark
{
readonly UnleashContext context = new();
readonly DefaultUnleash client = new(new UnleashSettings());
public Benchmark()
{
} …
```

Logger Improvements

---

src/Unleash/Variants/VariantUtils.cs

In continuing to look for performance hotspots after the latest release, `VariantUtils.SelectVariant` was identified as an area for improvement.
In the PR three changes were made to improve performance:
- totalWeight was not needed, per the docs this will always be 100%. This removes the Sum call which loops over the list of variants.
- The FirstOrDefault call was removed, this allows for us to loop over the list of variants only once.
- We check if there are any overrides before calling Any.
Using `BenchmarkerDotNet` the following benchmarks were run:
```csharp
[MemoryDiagnoser]
public class BenchmarksNoOverride
{
readonly ActivationStrategy defaultStrategy = new ActivationStrategy("default", new Dictionary<string, string>());
readonly FeatureToggle toggle;
readonly UnleashContext …
```

Improve SelectVariant performance

---

src/Unleash/Strategies/ConstraintUtils.cs
tests/Unleash.Tests/Integration/ClientSpecificationTests.cs

When using the IN and NOT_IN operators with the 'inverted' option turned on, the 'inverted' flag was previously ignored. This PR addresses this issue by ensuring that when 'inverted' is applied, it effectively inverts the result.

fix: IN and NOT_IN Inverted now actually inverts the result

---

src/Unleash/Strategies/Constraints/SemverConstraintOperator.cs
tests/Unleash.Tests/Strategy/Constraints/SemverConstraintOperator_Tests.cs

This patches the logging in the semver constraint to actually take the parameter that it needs to log, rather than throwing around a format string with nothing to format into it. This would previously cause some log implementations to crash and others to log a very unhelpful error message.

fix: make semver logging actually log context value that failed parsing

---

src/Unleash/Unleash.csproj

Updates the license declaration to use PackageLicenseExpression rather than PackageLicenseUrl, since that's been deprecated

chore: update license in csproj to use PackageLicenseExpression

---

src/Unleash/Communication/UnleashApiClient.cs

Fixes https://github.com/Unleash/unleash-client-dotnet/issues/206
* Hardware:
* Toolchain:
* SDK:

fix: etag empty body

---

src/Unleash/ClientFactory/UnleashClientFactory.cs
src/Unleash/Communication/IUnleashApiClient.cs
src/Unleash/Communication/UnleashApiClient.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/Scheduling/FetchFeatureTogglesTask.cs
src/Unleash/UnleashSettings.cs
tests/Unleash.Tests/ClientFactory/SyncStartupUnitTest.cs
tests/Unleash.Tests/ExampleTests.cs
tests/Unleash.Tests/IOTests.cs
tests/Unleash.Tests/Internal/ErrorEvents_Tests.cs
tests/Unleash.Tests/Internal/TogglesUpdatedEvent_Tests.cs
tests/Unleash.Tests/Mock/MockApiClient.cs
tests/Unleash.Tests/MockedUnleashSettings.cs

Failing fetches should throw during synchronous initializations.
Introduces a way to get this done that should be forwards and backwards compatible, but has a small public signature change in the ApiClient used internally.
Fixes #210 
- Added unit tests
- Ran existing tests

fix: throw when fetch features fails

---

README.md
Unleash.sln

- Should now not throw warnings or errors while building the solution with .NET 6++
- Project still there, just not in use in the SLN
- Adds some documentation to the README on how development works and requirements
- Adds documentation on doing releases

chore:dev improvements

---

README.md

I run into a build error if I don't specify this. It's specified in other examples so I think it's probably a typo?

Fixed typo with types in Readme

---

src/Unleash/Internal/UnleashServices.cs
src/Unleash/Metrics/ClientMetrics.cs
src/Unleash/Metrics/ClientRegistration.cs
src/Unleash/Metrics/MetricsMetadata.cs
tests/Unleash.Tests/Communication/UnleashApiClient_RegisterClient_Tests.cs
tests/Unleash.Tests/Communication/UnleashApiClient_SendMetrics_Tests.cs
tests/Unleash.Tests/Metrics/MetricsMetadataTests.cs

Needs #229, otherwise it'll be noisy
This adds metadata to the metrics and registration calls. This has a few sharp edges to it:
- Insofar as I can tell, there's no reliable way to get the version of the CLR or framework when running in C#. Everything has some details where it won't work on something. I've chosen to go with some degenerate string splitting + a compiler directive for older versions, which should give us enough information to know what's happening in the wild and always return "something"
- The design of the way async tasks work in this SDK needs to be rewritten to reduce the coupling between async stuff and business logic stuff. Right now there's no clean way to separate these two, which means there's no good way to extend the metrics/registration in a way that isn't …

feat: extend metrics with metadata

---

README.md
src/Unleash/Communication/UnleashApiClient.cs

Resets stream position to 0 every time a call to serializer has been made.
Fixes #222 
Tested this locally, should work fine with existing code bases already calling stream.Position = 0 on their serializer implementations

feat: always reset stream position after call to serializer

---

src/Unleash/Unleash.csproj

In preparation for [Yggdrasil PR](https://github.com/Unleash/unleash-client-dotnet/pull/224), remove all .NET framework versions < 4.7.2. We're keeping .NET Standard 2.0

chore: remove unsupported .NET framework versions

---

src/Unleash/Internal/UnleashExtensions.cs

Removes the dynamic parameters and their required type checks from the scheduler extensions and replaces with overloads for the two types we do expect as parameters: int and TimeSpan

chore: use method signature overloads instead of dynamic in scheduler

---

src/Unleash/DefaultUnleash.cs
src/Unleash/IUnleash.cs
src/Unleash/Internal/IToggleBootstrapProvider.cs
src/Unleash/Utilities/ToggleBootstrapFileProvider.cs
src/Unleash/Utilities/ToggleBootstrapUrlProvider.cs

Deprecations in preparation of [Yggdrasil PR](https://github.com/Unleash/unleash-client-dotnet/pull/224) that removes some public APIs

chore: prepare for Yggdrasil with deprecations of changing API

---

src/Unleash/UnleashSettings.cs

Deprecates ProjectId and Environment properties of UnleashSettings with an upcoming removal notice and gentle push towards API token scopes.

chore: deprecate no longer supported projectId and environment config settings

---

README.md

The formatting header was its own top-level header with "release
process" nested under it. I'm assuming it should've been one level
deeper (the same as release process).
Also, "other information" isn't really development stuff, so let's
raise it.

chore: change some header levels in README.md

---

src/Unleash/UnleashContext.cs
tests/Unleash.Tests/Strategy/Constraints/DateConstraintOperator_Tests.cs
tests/Unleash.Tests/UnleashContextTests.cs

Change `UnleashContext.GetByName` to return `CurrentTime` when `contextName` is `"currentTime"` (or `DateTimeOffset.UtcNow` when `UnleashContext.CurrentTime` is not set).
Also, I suspect the `else` branch of `if (!string.IsNullOrWhiteSpace(contextValue))` in `DateConstraintOperator.Evaluate` is wrong: I don't see why we would use `context.CurrentTime` if there is no value for the `ContextName` specified in the constraint. It should only be done if the `ContextName` is `"currentTime"` (but it would be redundant anyway after my change). I think that whole `else` branch should be removed. I didn't make that change yet, wanted to check with you guys first.
Fixes #245
Unit tests
* Firmware version: not relevant
* Hardware: …

Fix currentTime constraint when CurrentTime is not explicitly set

---

src/Unleash/Strategies/Constraints/DateConstraintOperator.cs

This just removes the `else` statement code here and makes the `if` the only code path.
The `else` is now redundant, based on this PR #246 which forces the context to always have a current time

chore: remove unnecessary else branch in date constraint

---

src/Unleash/DefaultUnleash.cs
src/Unleash/IUnleash.cs
src/Unleash/Internal/ToggleDefinition.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/Internal/Variant.cs
src/Unleash/Unleash.csproj
tests/Unleash.Tests/DefaultUnleashTests.cs
tests/Unleash.Tests/Integration/ClientSpecificationTests.cs
tests/Unleash.Tests/Integration/TestCaseVariant.cs

Adds a method to list the features known to the SDK. This is intended to replace the legacy option to access the feature flags directly, which is typically used to iterate the known flags and evaluate them all
There's a bunch of noise her moving from `IsEnabled` to `Enabled` in the engine but that's all internal
Also fixes the client spec header because that's wantonly out of sync at this point

feat: allow for listing the flags known to the SDK

---

src/Unleash/Communication/UnleashApiClient.cs

Sending this multiple times breaks the Unleash header validation and metrics/registration get rejected

chore: only send the JSON header once when sending metrics and registration

---

samples/DotnetCore/Program.cs
src/Unleash/ClientFactory/IUnleashClientFactory.cs
src/Unleash/ClientFactory/UnleashClientFactory.cs
src/Unleash/DefaultUnleash.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/Strategies/IStrategy.cs

Adds an adaptor for Yggdrasil ->  Legacy strategies so we don't have to leak out Yggdrasil abstractions. The barebones interface doesn't work because the method signature requires an Yggdrasil type - the Context.
Not tested automatically because it's all just plumbing but most of the existing tests already cover the Unleash constructor and manually tested through the example project

chore: swap out leaky yggdrasil custom strategy for an internal abstraction

---

README.md

Rewrites the project scoping section to revolve around using project scoped API tokens

docs: rewrite project scoping to involve using scoped api tokens

---

src/Unleash/Communication/UnleashApiClient.cs

Initializes a metric bucket with default values if the send metrics bucket comes back as null from the engine.
This lets us keep metrics as a heartbeat even when buckets are empty
This does not introduce the 10min hold off that Ruby does. Should it?

fix: send default buckets instead of null metrics buckets as they cause 400s

---

src/Unleash/Communication/UnleashApiClient.cs
src/Unleash/Communication/UnleashApiClientRequestHeaders.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/UnleashSettings.cs
tests/Unleash.Tests/Communication/CustomHeadersUnitTest.cs
tests/Unleash.Tests/Communication/MockHttpClient.cs
tests/Unleash.Tests/Communication/UnleashApiClient_Project_Tests.cs
tests/Unleash.Tests/UnleashSettingsTests.cs

Identification headers consistent with other Unleash SDKs.
> This PR adds standardized client identification headers to the feature and metrics calls that the client makes to Unleash. The headers are:
> - `x-unleash-appname`: the name of the application that is using the client. `UNLEASH-APPNAME` will be deleted in another PR (expand/contract pattern)
> - `x-unleash-connection-id`: an internal unique identifier for the current instance of the client generated by the built-in crypto lib
> - `x-unleash-sdk`: sdk information in the format `unleash-client-<language>:<version>`
> 
> All the headers are intended for the Unleash team. Changes should be implemented in a way that does not change SDK behavior in a significant way.
> The main use cases we have are:
> * capacity planning by knowing …

feat: client identification headers

---

src/Unleash/Communication/UnleashApiClient.cs
tests/Unleash.Tests/Communication/CustomHeadersUnitTest.cs

x- headers are deprecated (https://datatracker.ietf.org/doc/html/rfc6648). Let's use unleash- instead.

fix: drop x prefix

---

src/Unleash/Communication/UnleashApiClient.cs
tests/Unleash.Tests/Communication/CustomHeadersUnitTest.cs
tests/Unleash.Tests/Communication/RequestMessageHeadersTest.cs

Prevent unleash-connection-id overwrite with a custom header.

fix: prevent connection overwrite

---

src/Unleash/UnleashSettings.cs

Make sure the SDK follows the default fetch interval as other SDKs.

feat: Make the SDK follow default fetch interval

---

.github/workflows/prs.yml

Removes the dotnet-format tool install step from the workflow as should be included in >= .net 6 preview 7

chore(workflow): remove redundant dotnet-format tool install 

---

src/Unleash/Communication/UnleashApiClient.cs
src/Unleash/Communication/UnleashApiClientRequestHeaders.cs
src/Unleash/Metrics/ClientMetrics.cs
src/Unleash/Metrics/ClientRegistration.cs
tests/Unleash.Tests/Communication/CustomHeadersUnitTest.cs
tests/Unleash.Tests/Communication/UnleasRequestBodyUnitTest.cs

Connection id is now on all headers and metrics/register endpoint.
Interval is on metrics and feature fetch.

feat: connectionId and interval in headers

---

src/Unleash/Unleash.csproj

Bumps Yggdrasil dependency to 1.0.6 (fix for missing musl libraries)

chore: bump yggdrasil to 1.0.6

---

src/Unleash/Unleash.csproj
tests/Unleash.Tests/Unleash.Tests.csproj
tests/Unleash.Tests/packages.config

Cleans up no longer used dependencies NuGet.Versioning and murmurhash

chore: remove nuget.versioning and murmurhash dependencies no longer needed

---

src/Unleash/IUnleash.cs

We've had this method in the DefaultUnleash object for quite some time, and have #145 open to add support for it.
This PR adds it to the IUnleash instance as well to solve the issue

chore: add getvariant with context and no default variant to IUnleash

---

.github/workflows/release.yml

Should in theory let us release patches off the old v4 branch

chore: relax branch constraint on release action

---

README.md
src/Unleash/Communication/UnleashApiClient.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/Streaming/StreamingFeatureFetcher.cs
src/Unleash/UnleashSettings.cs
tests/Unleash.Tests/Streaming/StreamingFeatureFetcherTests.cs

Does a getstate from Ygg whenever a streaming update has been sent to take_state, and pipes that through to the backup file.

Updating the backup file whenever a streaming update is processed by Ygg

---

src/Unleash/Streaming/StreamingFeatureFetcher.cs

fixes an issue where not adding a trailing / after .../api would cause api portion to be removed before merging with relative uri when using streaming

chore: amend uris missing trailing slash before adding relative uri

---

src/Unleash/ClientFactory/UnleashClientFactory.cs
src/Unleash/Internal/UnleashServices.cs
src/Unleash/Scheduling/SystemTimerScheduledTaskManager.cs
src/Unleash/UnleashSettings.cs
tests/Unleash.Tests/ClientFactory/SyncStartupUnitTest.cs

This PR fixes the issue with setting up a new Unleash instance after failing a synchronized initialization where the timer collection would stay around after the error and prevent newing up new instances with the same unleash settings object.
This also fixes a cleanup issue where disposing timers could lead to errors

fix: dispose timers and fix disposal issues
